config/routes.rb
DevImpact1::Application.routes.draw do
  resources :developers

end

app/models/developer.rb
class Developer < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/developers_controller.rb
class DevelopersController < ApplicationController
  # GET /developers
  # GET /developers.xml
  def index
    @developers = Developer.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @developers }
    end
  end

  # GET /developers/1
  # GET /developers/1.xml
  def show
    @developer = Developer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @developer }
    end
  end

  # GET /developers/new
  # GET /developers/new.xml
  def new
    @developer = Developer.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @developer }
    end
  end

  # GET /developers/1/edit
  def edit
    @developer = Developer.find(params[:id])
  end

  # POST /developers
  # POST /developers.xml
  def create
    @developer = Developer.new(params[:developer])

    respond_to do |format|
      if @developer.save
        format.html { redirect_to(@developer, :notice => 'Developer was successfully created.') }
        format.xml  { render :xml => @developer, :status => :created, :location => @developer }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @developer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /developers/1
  # PUT /developers/1.xml
  def update
    @developer = Developer.find(params[:id])

    respond_to do |format|
      if @developer.update_attributes(params[:developer])
        format.html { redirect_to(@developer, :notice => 'Developer was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @developer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /developers/1
  # DELETE /developers/1.xml
  def destroy
    @developer = Developer.find(params[:id])
    @developer.destroy

    respond_to do |format|
      format.html { redirect_to(developers_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/developers_helper.rb
module DevelopersHelper
end

app/views/developers/_form.html.erb
<%= form_for(@developer) do |f| %>
  <% if @developer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@developer.errors.count, "error") %> prohibited this developer from being saved:</h2>

      <ul>
      <% @developer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :background %><br />
    <%= f.text_area :background %>
  </div>
  <div class="field">
    <%= f.label :exp_java %><br />
    <%= f.check_box :exp_java %>
  </div>
  <div class="field">
    <%= f.label :exp_mysql %><br />
    <%= f.check_box :exp_mysql %>
  </div>
  <div class="field">
    <%= f.label :exp_webapps %><br />
    <%= f.check_box :exp_webapps %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/developers/edit.html.erb
<h1>Editing developer</h1>

<%= render 'form' %>

<%= link_to 'Show', @developer %> |
<%= link_to 'Back', developers_path %>

app/views/developers/index.html.erb
<h1>Listing developers</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Background</th>
    <th>Exp java</th>
    <th>Exp mysql</th>
    <th>Exp webapps</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @developers.each do |developer| %>
  <tr>
    <td><%= developer.name %></td>
    <td><%= developer.email %></td>
    <td><%= developer.background %></td>
    <td><%= developer.exp_java %></td>
    <td><%= developer.exp_mysql %></td>
    <td><%= developer.exp_webapps %></td>
    <td><%= link_to 'Show', developer %></td>
    <td><%= link_to 'Edit', edit_developer_path(developer) %></td>
    <td><%= link_to 'Destroy', developer, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Developer', new_developer_path %>

app/views/developers/new.html.erb
<h1>New developer</h1>

<%= render 'form' %>

<%= link_to 'Back', developers_path %>

app/views/developers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @developer.name %>
</p>

<p>
  <b>Email:</b>
  <%= @developer.email %>
</p>

<p>
  <b>Background:</b>
  <%= @developer.background %>
</p>

<p>
  <b>Exp java:</b>
  <%= @developer.exp_java %>
</p>

<p>
  <b>Exp mysql:</b>
  <%= @developer.exp_mysql %>
</p>

<p>
  <b>Exp webapps:</b>
  <%= @developer.exp_webapps %>
</p>


<%= link_to 'Edit', edit_developer_path(@developer) %> |
<%= link_to 'Back', developers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DevImpact1</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>